# Generated by Django 6.0.7 on 2026-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_produitvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Un nom simple pour identifier cette annonce ', max_length=255, verbose_name="Nom de l'annonce")),
                ('image', models.ImageField(help_text="Télécharge ici l'image de ton annonce publicitaire", upload_to='annonces/', verbose_name="Image de l'annonce")),
                ('actif', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
    ]
