# Generated by Django 6.0.7 on 2026-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_anonce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anonce',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produitvariant',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProduitVariant',
        ),
    ]
