# Generated by Django 6.0.7 on 2026-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_delete_anonce_remove_product_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du quartier')),
                ('ville', models.CharField(max_length=100, unique=True, verbose_name='Nom de la ville')),
                ('latitude_centre', models.FloatField(verbose_name='Latitude du centre')),
                ('longitude_centre', models.FloatField(verbose_name='Longitude du centre')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['nom'],
            },
        ),
    ]
