# Generated by Django 6.0.7 on 2026-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartier',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Nom de la ville'),
        ),
    ]
