# Generated by Django 6.0.7 on 2026-07-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_delete_user'),
        ('shop', '0006_alter_quartier_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name="Titre de l'annonce")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (FCFA)')),
                ('type_bien', models.CharField(choices=[('studio', 'Studio'), ('appartement', 'Appartement'), ('chambre', 'Chambre'), ('maison', 'Maison / Villa'), ('terrain', 'Terrain')], default='appartement', max_length=20)),
                ('statut', models.CharField(choices=[('louer', 'À Louer'), ('vendre', 'À Vendre')], default='louer', max_length=10)),
                ('chambres', models.PositiveIntegerField(default=0, verbose_name='Nombre de chambres')),
                ('douches', models.PositiveIntegerField(default=0, verbose_name='Nombre de douches')),
                ('cuisine', models.PositiveIntegerField(default=0, verbose_name='Nombre de cuisine')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bailleur', models.ForeignKey(limit_choices_to={'role': 'PROPRIETAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='account.profile', verbose_name='Bailleur / Agent responsable')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='shop.quartier')),
            ],
            options={
                'verbose_name': 'Bien Immobilier',
                'verbose_name_plural': 'Biens Immobiliers',
                'ordering': ['-cree_le'],
            },
        ),
    ]
