# Generated by Django 6.0.7 on 2026-07-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_bienimmobilier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens/', verbose_name='Image du bien')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.bienimmobilier', verbose_name='Bien immobilier')),
            ],
            options={
                'verbose_name': 'Image de bien',
                'verbose_name_plural': 'Images de biens',
            },
        ),
    ]
