# Generated by Django 6.0.7 on 2026-07-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_delete_user'),
        ('shop', '0009_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens_reserves', to='account.profile'),
        ),
    ]
